### ISSUE TITLE
ECIP-1019 - Epoch Decay Monetary Policy Proposal

### ISSUE THREAD

**Issue by mikeyb** [ethereumproject/EIPs#25]
####  Proposed Ethereum Classic Monetary Policy

[Source](https://docs.google.com/spreadsheets/d/1mPPfzLtJ5V7mz2gz5hyqTytJSyoQ3oRyvs7CAIoMnH8/edit#gid=1694393546)

![image alt text](https://cloud.githubusercontent.com/assets/36461/22135058/0cf73242-de89-11e6-945e-c1e2cd2105d2.png)

#####  Pre-calculated Decay Options

|Decay Option #|Decay Percentage|Miner Decay Amount|Uncle Decay Amount|Years to Decay|Estimated Supply (Current Reward)|Block Height Reward Ends|
|--------------|----------------|------------------|------------------|--------------|---------------------------------|------------------------|
|1|5.00%|0.2500|0.02500|5.236872146|99,851,032|11,010,000|
|2|4.00%|0.2000|0.02000|5.950342466|100,226,032|12,510,000|
|3|3.00%|0.1500|0.01500|7.139454909|100,851,532|15,009,990|
|4|2.00%|0.1000|0.01000|9.517694064|102,101,032|20,010,000|
|5|1.00%|0.0500|0.00500|16.65239726|105,851,032|35,010,000|
|6|0.50%|0.0250|0.00250|30.92180365|113,351,032|65,010,000|
|7|0.25%|0.0125|0.00125|59.46061644|128,351,032|125,010,000|

###  Rationale

-  Gradual decay of rewards to 0.  Length of time depends on decay rate. 
-  Dead simple to understand.
   -  Starting at Epoch 167 (Block # 5,010,000) the decay activates
   -  Rewards for mining block start at: `5 ETC`
   -  Rewards for mining uncled start at: `0.5 ETC`
   -  Decay persists every 10 Epoch until reaching 0, in which gas costs are the only collected fees
-  Simple, nearly straight line supply growth on chart.  Only fluctuation is gas rewards/uncle rates, as this is not predictable in all long term models.
-  The Epoch Decay model provides a balance between providing an acceptable depreciating distribution rate for rewarding high risk investment into the system, and maintaining an active supply production over time, maintaining a future supply rate and keeping that potential price of the ethereum token suppressed enough to ensure transaction prices can remain lower than if the supply were to reduce to zero at an earlier date. This serves as a "blow off valve" for price increase in the case that a dynamic gas model cannot be implemented for the foreseeable future. 
-  Having the monetary policy reward decay begin at block 5,010,000 (Epoch 167) provides a balance between delaying the implementation to provide enough time for code development and testing, and accelerating the implementation to provide an incentive to potential early adopters and high risk investors. Based on community discussion, beginning before block 4,000,000 is too soon for development, testing, and implementation of the policy, and later than block 6,000,000 is too long to interest many potential early adopters/investors. 
-  Not changing the monetary policy of ETC provides no benefit to risk taking early on in the life of the system, speculation wise. It will be difficult for the network to bootstrap its security. While bitcoin has what is considered to be the generally accepted ideal monetary policy, with its 50% reduction every four years, this model is not likely to yield optimal investment for ETC. If ETC were to adopt the bitcoin halving model, it is arguable that too much of the supply would be produced too soon: 50% of the estimated total ETC supply would be mined 75% sooner than traditional bitcoin because of the pre-mine of 72,002,454.77 ETC that was initially created in the genesis block. While the Epoch Decay model does not completely eliminate the effects of the premine, since 50% of total estimated production occurs sooner than would the bitcoin model, it makes up for this, to an extent, depending on how much decay is decided upon. 
-  In the current ETC reward schedule, the total reward for uncles is higher than the reward received by the miner who also includes uncles. In this state, a miner is significantly diluting the value of his reward by including these uncled blocks. By equalizing the rewards to uncle block miners with the rewards to miners who include an uncle block, the reward structure is more fairly distributed. In addition, equalizing the uncle rewards reduces the incentive for miners to set up an ETC "uncle farm," and instead drives them to better secure the network by competing for the latest "real block." 
-  Because the rate at which uncled blocks can vary with extreme, reducing the reward for uncle blocks assists considerably with being able to forecast the true upper bound of the total ETC that will ultimately exist in the system. 
-  The model is the best attempt at balancing the needs to incentivize high risk investment into the system in order to bootstrap security and create a potential user base, be easy to understand, include a reduction to the rate of production of ETC over time, include an upper bound on supply, and also provide for a long term production of the ETC token.

###  Implementation

*  Timeline for the implementation and the code required to execute after approval.

**Comment by realcodywburns** [comment]
Closing issue per above reference
