### ISSUE TITLE
ECIP-1010 Delay Difficulty Bomb Explosion

### ISSUE THREAD

**Issue by arvicco** [ethereumproject/EIPs#3]

**Comment by arvicco** [comment]
This issue is dedicated to discussion of ECIP-1010 Delay Difficulty Bomb Explosion by @splix. 
Located here: https://github.com/ethereumproject/ECIPs/blob/master/EIPs/ECIP-1010.md

**Comment by elaineo** [comment]
hey, i'm gonna merge this issue with the other one, because it looks like we were opening issues at the same time...

**Comment by arvicco** [comment]
I think the Issue for discussion should clearly identify ECIP being discussed and it's location.
