### ISSUE TITLE
ECIP-? Remove Old EIPs

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/EIPs#48]
```
    ECIP: ?
    Title: Remove Old EIPs
    Author: Wei Tang <hi@that.world>
    Discussions-To: hi@that.world
    Status: Draft
    Type: Process
    Created: 2017-04-29
```

### Abstract

Currently we have `EIP-1001` to `EIP-1009` in this repository. Those are duplicates of the `ethereum/EIPs`. Plus, even the Ethereum Foundation changed their EIP process that new EIPs are not created in this way.

As those are not maintained by us, I suggest we remove those EIPs and only put ECIPs in this repository.

**Comment by elaineo** [comment]
I agree.

**Comment by splix** [comment]
I agree, we can delete them and reference original EIP if we'll need

**Comment by realcodywburns** [comment]
Ack

**Comment by sorpaas** [comment]
I'm going to close this as #55 is merged. This is not actually an ECIP but some structural changes.
